[workspace]
resolver = "2"
members = [
    "rehash-cli", "rehash-generator", "rehash-vault",
]

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"

